### PR TITLE
Bug fix 'max nested calls' #7 - support PHP >= 5.4.0

### LINKED ISSUE #7: Lumen 5.0 : Fatal error: Maximum function nesting level of '100' reached
The following error occurs when using this package with Lumen 5.0 :

```
( ! ) Fatal error: Maximum function nesting level of '100' reached, aborting! in C:\wamp\www\lumen\vendor\illuminate\support\ServiceProvider.php on line 220

Call Stack
#   Time    Memory  Function    Location
1   0.0000  153952  {main}( )   ..\index.php:0
2   0.1406  2854112 Laravel\Lumen\Application->run( )   ..\index.php:31
3   0.1406  2854160 Laravel\Lumen\Application->dispatch( )  ..\Application.php:1037
4   0.1406  2860128 Laravel\Lumen\Application->sendThroughPipeline( )   ..\Application.php:1099
5   0.1406  2877432 Illuminate\Pipeline\Pipeline->then( )   ..\Application.php:1317
6   0.1406  2880704 call_user_func ( )  ..\Pipeline.php:101
7   0.1406  2880720 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )  ..\Pipeline.php:101
8   0.1562  2948712 Illuminate\Cookie\Middleware\EncryptCookies->handle( )  ..\Pipeline.php:125
9   0.1562  2963424 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )  ..\EncryptCookies.php:40
10  0.1562  3000504 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle( )  ..\Pipeline.php:125
11  0.1562  3000544 Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )  ..\AddQueuedCookiesToResponse.php:36
12  0.1562  3000584 Laravel\Lumen\Application->make( )  ..\Pipeline.php:124
13  0.1562  3000664 Illuminate\Container\Container->make( ) ..\Application.php:366
14  0.1562  3000664 Illuminate\Container\Container->build( )    ..\Container.php:659
15  0.1562  3000664 Illuminate\Container\Container->Illuminate\Container\{closure}( )   ..\Container.php:776
16  0.1562  3000712 Illuminate\Container\Container->build( )    ..\Container.php:229
17  0.1719  3036680 Illuminate\Container\Container->getDependencies( )  ..\Container.php:816
18  0.1719  3073760 Illuminate\Container\Container->resolveClass( ) ..\Container.php:851
19  0.1719  3073840 Laravel\Lumen\Application->make( )  ..\Container.php:890
20  0.1719  3073944 Illuminate\Container\Container->make( ) ..\Application.php:366
21  0.1719  3073944 Illuminate\Container\Container->build( )    ..\Container.php:659
22  0.1719  3073944 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
23  0.1719  3074096 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
24  0.1719  3074216 Laravel\Lumen\Application->make( )  ..\Application.php:721
25  0.1719  3074296 Illuminate\Container\Container->make( ) ..\Application.php:366
26  0.1719  3074296 Illuminate\Container\Container->build( )    ..\Container.php:659
27  0.1719  3074296 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
28  0.1719  3074432 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
29  0.1719  3074552 Laravel\Lumen\Application->make( )  ..\Application.php:721
30  0.1719  3074632 Illuminate\Container\Container->make( ) ..\Application.php:366
31  0.1719  3074632 Illuminate\Container\Container->build( )    ..\Container.php:659
32  0.1719  3074632 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
33  0.1719  3074768 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
34  0.1719  3074888 Laravel\Lumen\Application->make( )  ..\Application.php:721
35  0.1719  3074968 Illuminate\Container\Container->make( ) ..\Application.php:366
36  0.1719  3074968 Illuminate\Container\Container->build( )    ..\Container.php:659
37  0.1719  3074968 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
38  0.1719  3075104 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
39  0.1719  3075224 Laravel\Lumen\Application->make( )  ..\Application.php:721
40  0.1719  3075304 Illuminate\Container\Container->make( ) ..\Application.php:366
41  0.1719  3075304 Illuminate\Container\Container->build( )    ..\Container.php:659
42  0.1719  3075304 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
43  0.1719  3075440 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
44  0.1719  3075560 Laravel\Lumen\Application->make( )  ..\Application.php:721
45  0.1719  3075640 Illuminate\Container\Container->make( ) ..\Application.php:366
46  0.1719  3075640 Illuminate\Container\Container->build( )    ..\Container.php:659
47  0.1719  3075640 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
48  0.1719  3075776 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
49  0.1719  3075896 Laravel\Lumen\Application->make( )  ..\Application.php:721
50  0.1719  3075976 Illuminate\Container\Container->make( ) ..\Application.php:366
51  0.1719  3075976 Illuminate\Container\Container->build( )    ..\Container.php:659
52  0.1719  3075976 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
53  0.1719  3076112 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
54  0.1719  3076232 Laravel\Lumen\Application->make( )  ..\Application.php:721
55  0.1719  3076312 Illuminate\Container\Container->make( ) ..\Application.php:366
56  0.1719  3076312 Illuminate\Container\Container->build( )    ..\Container.php:659
57  0.1719  3076312 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
58  0.1719  3076448 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
59  0.1719  3076568 Laravel\Lumen\Application->make( )  ..\Application.php:721
60  0.1719  3076648 Illuminate\Container\Container->make( ) ..\Application.php:366
61  0.1719  3076648 Illuminate\Container\Container->build( )    ..\Container.php:659
62  0.1719  3076648 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
63  0.1719  3076784 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
64  0.1719  3076904 Laravel\Lumen\Application->make( )  ..\Application.php:721
65  0.1719  3076984 Illuminate\Container\Container->make( ) ..\Application.php:366
66  0.1719  3076984 Illuminate\Container\Container->build( )    ..\Container.php:659
67  0.1719  3076984 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
68  0.1719  3077120 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
69  0.1719  3077240 Laravel\Lumen\Application->make( )  ..\Application.php:721
70  0.1719  3077320 Illuminate\Container\Container->make( ) ..\Application.php:366
71  0.1719  3077320 Illuminate\Container\Container->build( )    ..\Container.php:659
72  0.1719  3077320 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
73  0.1719  3077456 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
74  0.1719  3077576 Laravel\Lumen\Application->make( )  ..\Application.php:721
75  0.1719  3077656 Illuminate\Container\Container->make( ) ..\Application.php:366
76  0.1719  3077656 Illuminate\Container\Container->build( )    ..\Container.php:659
77  0.1719  3077656 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
78  0.1719  3077792 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
79  0.1719  3077912 Laravel\Lumen\Application->make( )  ..\Application.php:721
80  0.1719  3077992 Illuminate\Container\Container->make( ) ..\Application.php:366
81  0.1719  3077992 Illuminate\Container\Container->build( )    ..\Container.php:659
82  0.1719  3077992 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
83  0.1719  3078128 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
84  0.1719  3078248 Laravel\Lumen\Application->make( )  ..\Application.php:721
85  0.1719  3078328 Illuminate\Container\Container->make( ) ..\Application.php:366
86  0.1719  3078328 Illuminate\Container\Container->build( )    ..\Container.php:659
87  0.1719  3078328 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
88  0.1719  3078464 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
89  0.1719  3078584 Laravel\Lumen\Application->make( )  ..\Application.php:721
90  0.1719  3078664 Illuminate\Container\Container->make( ) ..\Application.php:366
91  0.1719  3078664 Illuminate\Container\Container->build( )    ..\Container.php:659
92  0.1719  3078664 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
93  0.1719  3078800 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
94  0.1719  3078920 Laravel\Lumen\Application->make( )  ..\Application.php:721
95  0.1719  3079000 Illuminate\Container\Container->make( ) ..\Application.php:366
96  0.1719  3079000 Illuminate\Container\Container->build( )    ..\Container.php:659
97  0.1719  3079000 Laravel\Lumen\Application->Laravel\Lumen\{closure}( )   ..\Container.php:776
98  0.1719  3079136 Laravel\Lumen\Application->loadComponent( ) ..\Application.php:627
99  0.1719  3079424 Laravel\Lumen\Application->register( )  ..\Application.php:718
```

I did some **debugging** and found the following :
-> In `HtmlServiceProvider.php` and in response to issue #5, You attempt to register the `Session` component like this :

``` PHP
    protected function registerIlluminateSession(){
        if (!isset($this->app['session.store'])) {
            $this->app->configure('session');

            if(!$this->app['config']->has('session.driver')) {
                $this->app['config']->set('session.driver', 'file');
            } 

            $this->app->register(\Illuminate\Session\SessionServiceProvider::class);
        }         
    }
```

You first check to see if the `session.store` key exists in the `container` then you register it if not.
This will work with Lumen 5.2 but not 5.0 or 5.1,
**Why ?**
Because `isset($this->app['session.store'])` will always return false even if the container has the `session` bindings that's because `session.store` doesn't exist in the container itself but in the `Application`'s `$availableBindings[]` array.

So to fix the problem we need to check for `session.store` in `Application->availableBindings`.

I'll issue a PR to fix it.
Also in my PR I'll make it support php >= 5.4.0 which the whole package code supports it except in the previous block of code in `\Illuminate\Session\SessionServiceProvider::class` which can be fixed by replacing it with it's string representation (`'Illuminate\Session\SessionServiceProvider'`).

### PR DESCRIPTION
**Pull request by mmghv**
- fixes #7 :
  (FixFatal error: Maximum function nesting level of '100' reached, aborting!) with Lumen 5.0 or 5.1
- support PHP >= 5.4.0

### CODE REVIEW

**Review by mmghv — COMMENTED** [review]
Lumen 5.0 requires PHP>=5.4.0,
This package is for Lumen ~5.0,
So this package should require the same PHP version (>=5.4.0)

File: src/HtmlServiceProvider.php [hunk 1]
```diff
@@ -33,16 +33,17 @@ public function register()
...
             
-            if(!$this->app['config']->has('session.driver')) {
+            if (!$this->app['config']->has('session.driver')) {
                 $this->app['config']->set('session.driver', 'file');
-            } 
+            }
 
-            $this->app->register(\Illuminate\Session\SessionServiceProvider::class);
-        }         
+            $this->app->register('Illuminate\Session\SessionServiceProvider');
```
Comment (mmghv) [inline src/HtmlServiceProvider.php:45]: Here we used `'Illuminate\Session\SessionServiceProvider'` instead of `\Illuminate\Session\SessionServiceProvider::class` to allow support for PHP 5.4.0

**Review by mmghv — COMMENTED** [review]
Replace PHP 5.5 `::Class` keyword

**Comment by mmghv** [comment]
Thank you,
Can you make a new release please so I can reference it?

**Comment by vluzrmos** [comment]
Yes,I'm sorry for that
